<?php

// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-data.php from spec/data. Do not edit this file.

declare(strict_types=1);

namespace Gatepost\Postcode\Internal;

/**
 * The values in the JSON files in spec/data.
 *
 * @internal
 */
final class SpecData
{
    /**
     * The most code points that parse reads. Longer input fails before normalize runs.
     */
    public const MAX_INPUT_CODE_POINTS = 64;

    /**
     * State codes and names.
     */
    public const STATES = [
        'AB' => 'Abia',
        'AD' => 'Adamawa',
        'AK' => 'Akwa Ibom',
        'AN' => 'Anambra',
        'BA' => 'Bauchi',
        'BE' => 'Benue',
        'BR' => 'Borno',
        'BY' => 'Bayelsa',
        'CR' => 'Cross River',
        'DE' => 'Delta',
        'EB' => 'Ebonyi',
        'ED' => 'Edo',
        'EK' => 'Ekiti',
        'EN' => 'Enugu',
        'FC' => 'Federal Capital Territory',
        'GM' => 'Gombe',
        'IM' => 'Imo',
        'JI' => 'Jigawa',
        'KD' => 'Kaduna',
        'KE' => 'Kebbi',
        'KG' => 'Kogi',
        'KN' => 'Kano',
        'KT' => 'Katsina',
        'KW' => 'Kwara',
        'LA' => 'Lagos',
        'NA' => 'Nasarawa',
        'NI' => 'Niger',
        'OG' => 'Ogun',
        'ON' => 'Ondo',
        'OS' => 'Osun',
        'OY' => 'Oyo',
        'PL' => 'Plateau',
        'RI' => 'Rivers',
        'SK' => 'Sokoto',
        'TA' => 'Taraba',
        'YB' => 'Yobe',
        'ZA' => 'Zamfara',
    ];

    /**
     * Each segment from the least to the most precise, with its place in a compact code.
     */
    public const SEGMENTS = [
        'state' => ['start' => 0, 'length' => 2, 'end' => 2, 'characters' => 'letters', 'minimum' => null],
        'lga' => ['start' => 2, 'length' => 2, 'end' => 4, 'characters' => 'digits', 'minimum' => 1],
        'district' => ['start' => 4, 'length' => 3, 'end' => 7, 'characters' => 'letters-or-digits', 'minimum' => null],
        'area' => ['start' => 7, 'length' => 2, 'end' => 9, 'characters' => 'letters', 'minimum' => null],
        'unit' => ['start' => 9, 'length' => 2, 'end' => 11, 'characters' => 'digits', 'minimum' => 1],
    ];

    /**
     * GPS accuracy limits in metres. Each limit is inclusive.
     */
    public const PRECISION_THRESHOLDS = [
        ['maxAccuracyM' => 8, 'precision' => 'unit'],
        ['maxAccuracyM' => 20, 'precision' => 'area'],
        ['maxAccuracyM' => 50, 'precision' => 'district'],
    ];

    /**
     * The precision for an accuracy that no limit covers.
     */
    public const PRECISION_FALLBACK = 'lga';

    /**
     * Each separator that normalize removes, mapped to the empty string for strtr().
     */
    public const SEPARATORS = [
        "\u{0009}" => '',
        "\u{000A}" => '',
        "\u{000B}" => '',
        "\u{000C}" => '',
        "\u{000D}" => '',
        " " => '',
        "-" => '',
        "." => '',
        "\u{0085}" => '',
        "\u{00A0}" => '',
        "\u{00AD}" => '',
        "\u{1680}" => '',
        "\u{2000}" => '',
        "\u{2001}" => '',
        "\u{2002}" => '',
        "\u{2003}" => '',
        "\u{2004}" => '',
        "\u{2005}" => '',
        "\u{2006}" => '',
        "\u{2007}" => '',
        "\u{2008}" => '',
        "\u{2009}" => '',
        "\u{200A}" => '',
        "\u{200B}" => '',
        "\u{200C}" => '',
        "\u{200D}" => '',
        "\u{200E}" => '',
        "\u{200F}" => '',
        "\u{2010}" => '',
        "\u{2011}" => '',
        "\u{2012}" => '',
        "\u{2013}" => '',
        "\u{2014}" => '',
        "\u{2015}" => '',
        "\u{2028}" => '',
        "\u{2029}" => '',
        "\u{202F}" => '',
        "\u{205F}" => '',
        "\u{2060}" => '',
        "\u{2212}" => '',
        "\u{3000}" => '',
        "\u{FEFF}" => '',
    ];

    /**
     * Old 6-digit NIPOST postcodes. With D, $ does not match before a final line feed.
     */
    public const LEGACY_PATTERN = '/^[0-9]{6}$/D';

    /**
     * Typo fixes in digit segments.
     */
    public const DIGIT_FIXES = [
        'O' => '0',
        'I' => '1',
        'L' => '1',
    ];

    /**
     * Typo fixes in letter segments.
     */
    public const LETTER_FIXES = [
        '0' => 'O',
        '1' => 'I',
    ];
}
