<?php

// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

// Writes docs/api-dump.md: the public symbols of the package, read by reflection. These are the
// classes, interfaces and enums that composer.json maps to a folder, outside any Internal
// namespace, with their public constants, cases, properties and methods. Run `composer api:dump`
// after a change of the public interface (NPG-5, GIT-7). `composer api:dump:check` fails when the
// file is out of date. The script finds its classes through the PSR-4 map of composer.json and
// loads them with its own autoloader, so it needs no installed package.

namespace Gatepost\Postcode\Scripts;

use BackedEnum;
use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionClassConstant;
use ReflectionEnum;
use ReflectionEnumBackedCase;
use ReflectionIntersectionType;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionProperty;
use ReflectionType;
use ReflectionUnionType;
use RuntimeException;
use SplFileInfo;
use UnitEnum;

const DUMP_FILE = 'docs/api-dump.md';
const INTERNAL_NAMESPACE = 'Internal';
// PHP adds these methods and interfaces to each enum, so the keyword enum already says it.
const ENUM_METHODS = ['cases', 'from', 'tryFrom'];
const ENUM_INTERFACES = [UnitEnum::class, BackedEnum::class];
const SELF_NAMES = ['self', 'static', 'parent'];
const DUMP_NOTE = 'Do not edit this file. `composer api:dump` writes it from the public symbols of '
    . 'the package. It leaves out each `Internal` namespace and each symbol with `@internal` in '
    . 'its doc comment. It shows native types only, so a type that only a doc comment gives is '
    . 'not here. `composer api:dump:check` fails when this file is out of date.';

/**
 * @return array<mixed>
 */
function readComposerJson(string $root): array
{
    $path = "{$root}/composer.json";
    $json = \is_file($path) && \is_readable($path) ? \file_get_contents($path) : false;
    $composer = $json === false ? null : \json_decode($json, true);
    if (!\is_array($composer)) {
        throw new RuntimeException('Cannot read composer.json.');
    }

    return $composer;
}

/**
 * @param array<mixed> $composer
 *
 * @return array<string, string> Each PSR-4 prefix with its folder.
 */
function psr4Folders(array $composer, string $root): array
{
    $autoload = $composer['autoload'] ?? null;
    $map = \is_array($autoload) ? ($autoload['psr-4'] ?? null) : null;
    if (!\is_array($map) || $map === []) {
        throw new RuntimeException('composer.json needs an autoload.psr-4 map.');
    }
    $folders = [];
    foreach ($map as $prefix => $folder) {
        if (!\is_string($prefix) || !\is_string($folder)) {
            throw new RuntimeException('Each PSR-4 entry of composer.json must name one folder.');
        }
        $folders[$prefix] = $root . '/' . \rtrim($folder, '/');
    }

    return $folders;
}

/**
 * @param array<string, string> $folders
 */
function registerAutoloader(array $folders): void
{
    \spl_autoload_register(static function (string $name) use ($folders): void {
        foreach ($folders as $prefix => $folder) {
            $file = $folder . '/' . \str_replace('\\', '/', \substr($name, \strlen($prefix)));
            if (\str_starts_with($name, $prefix) && \is_file("{$file}.php")) {
                require_once "{$file}.php";
            }
        }
    });
}

/**
 * @param array<string, string> $folders
 *
 * @return list<string> Each class name that the PSR-4 map gives to a file outside Internal.
 */
function classNames(array $folders): array
{
    $names = [];
    foreach ($folders as $prefix => $folder) {
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($folder, FilesystemIterator::SKIP_DOTS),
        );
        foreach ($files as $file) {
            if (!$file instanceof SplFileInfo || $file->getExtension() !== 'php') {
                continue;
            }
            $path = \substr($file->getPathname(), \strlen($folder) + 1, -\strlen('.php'));
            $segments = \explode(\DIRECTORY_SEPARATOR, \dirname($path));
            if (!\in_array(INTERNAL_NAMESPACE, $segments, true)) {
                $names[] = $prefix . \str_replace(\DIRECTORY_SEPARATOR, '\\', $path);
            }
        }
    }
    \sort($names);

    return $names;
}

/**
 * @return ReflectionClass<object>
 */
function reflectSymbol(string $name): ReflectionClass
{
    if (\enum_exists($name)) {
        return new ReflectionEnum($name);
    }
    if (!\class_exists($name) && !\interface_exists($name)) {
        throw new RuntimeException(
            "{$name} is not a class, an interface or an enum. "
            . 'Check that the file name follows the class name.',
        );
    }

    return new ReflectionClass($name);
}

// The doc comments of the package say @internal for a public symbol that only the package calls.
function isInternal(string|false $docComment): bool
{
    return $docComment !== false && \str_contains($docComment, '@internal');
}

// A name inside the namespace of the symbol loses that namespace. Any other class name keeps its
// whole name, with a backslash in front, so that a reader cannot take it for a local name.
function relativeName(string $name, string $namespace): string
{
    $prefix = $namespace . '\\';

    return \str_starts_with($name, $prefix) ? \substr($name, \strlen($prefix)) : '\\' . $name;
}

function typeText(?ReflectionType $type, string $namespace): string
{
    if ($type instanceof ReflectionNamedType) {
        $name = $type->getName();
        $isClass = !$type->isBuiltin() && !\in_array($name, SELF_NAMES, true);
        $text = $isClass ? relativeName($name, $namespace) : $name;
        $isNullable = $type->allowsNull() && !\in_array($name, ['mixed', 'null'], true);

        return $isNullable ? "?{$text}" : $text;
    }
    if ($type instanceof ReflectionUnionType || $type instanceof ReflectionIntersectionType) {
        $separator = $type instanceof ReflectionUnionType ? '|' : '&';

        return \implode($separator, \array_map(
            static fn(ReflectionType $part): string => typeText($part, $namespace),
            $type->getTypes(),
        ));
    }

    return '';
}

function floatLiteral(float $value): ?string
{
    $json = \json_encode($value, JSON_PRESERVE_ZERO_FRACTION);

    return $json === false ? null : $json;
}

function stringLiteral(string $value): ?string
{
    if (\preg_match('/\A[ -~]*\z/', $value) !== 1) {
        return null;
    }

    return "'" . \strtr($value, ['\\' => '\\\\', "'" => "\\'"]) . "'";
}

// The script writes only the values that its tests cover. A value of another kind stops the run,
// so that the dump never holds a wrong or a missing value.
function literal(mixed $value, string $namespace): ?string
{
    return match (true) {
        $value === null => 'null',
        \is_bool($value) => $value ? 'true' : 'false',
        \is_int($value) => (string) $value,
        \is_float($value) => floatLiteral($value),
        \is_string($value) => stringLiteral($value),
        $value === [] => '[]',
        $value instanceof UnitEnum => relativeName($value::class, $namespace) . '::' . $value->name,
        default => null,
    };
}

function unwritable(string $what, mixed $value): RuntimeException
{
    $type = \is_string($value)
        ? 'string with a character outside printable ASCII'
        : \get_debug_type($value);

    return new RuntimeException(
        "Cannot write {$what}. The script writes null, booleans, numbers, printable ASCII text, "
        . "an empty array and enum cases, but the value has the type {$type}.",
    );
}

function parameterText(ReflectionParameter $parameter, string $namespace): string
{
    $type = typeText($parameter->getType(), $namespace);
    $text = ($type === '' ? '' : "{$type} ") . ($parameter->isPassedByReference() ? '&' : '')
        . ($parameter->isVariadic() ? '...' : '') . '$' . $parameter->name;
    if (!$parameter->isDefaultValueAvailable()) {
        return $text;
    }
    $default = $parameter->getDefaultValue();
    $owner = ($parameter->getDeclaringClass()->name ?? '') . '::'
        . $parameter->getDeclaringFunction()->name . '()';

    return $text . ' = ' . (literal($default, $namespace)
        ?? throw unwritable("the default value of \${$parameter->name} in {$owner}", $default));
}

/**
 * @param ReflectionClass<object> $class
 *
 * @return list<string>
 */
function caseLines(ReflectionClass $class, string $namespace): array
{
    if (!$class instanceof ReflectionEnum) {
        return [];
    }
    $lines = [];
    foreach ($class->getCases() as $case) {
        if (!$case instanceof ReflectionEnumBackedCase) {
            $lines[] = "case {$case->name};";
            continue;
        }
        $value = $case->getBackingValue();
        $what = "the value of the case {$class->name}::{$case->name}";
        $lines[] = "case {$case->name} = " . (literal($value, $namespace)
            ?? throw unwritable($what, $value)) . ';';
    }

    return $lines;
}

/**
 * @param ReflectionClass<object> $class
 *
 * @return list<string>
 */
function publicConstantLines(ReflectionClass $class, string $namespace): array
{
    $lines = [];
    foreach ($class->getReflectionConstants(ReflectionClassConstant::IS_PUBLIC) as $constant) {
        $isOwn = $constant->getDeclaringClass()->name === $class->name;
        if (!$isOwn || $constant->isEnumCase() || isInternal($constant->getDocComment())) {
            continue;
        }
        $value = $constant->getValue();
        $lines[] = ($constant->isFinal() ? 'final ' : '') . "public const {$constant->name} = "
            . (literal($value, $namespace) ?? throw unwritable(
                "the value of the constant {$class->name}::{$constant->name}",
                $value,
            )) . ';';
    }

    return $lines;
}

/**
 * @param ReflectionClass<object> $class
 *
 * @return list<string>
 */
function propertyLines(ReflectionClass $class, string $namespace): array
{
    // PHP gives each enum the properties name and value, and an enum cannot declare more.
    $properties = $class->isEnum() ? [] : $class->getProperties(ReflectionProperty::IS_PUBLIC);
    $lines = [];
    foreach ($properties as $property) {
        $isOwn = $property->getDeclaringClass()->name === $class->name;
        if (!$isOwn || isInternal($property->getDocComment())) {
            continue;
        }
        $type = typeText($property->getType(), $namespace);
        $lines[] = 'public ' . ($property->isStatic() ? 'static ' : '')
            . ($property->isReadOnly() ? 'readonly ' : '')
            . ($type === '' ? '' : "{$type} ") . '$' . $property->name . ';';
    }

    return $lines;
}

/**
 * @param ReflectionClass<object> $class
 */
function methodLine(ReflectionClass $class, ReflectionMethod $method, string $namespace): string
{
    $parameters = \array_map(
        static fn(ReflectionParameter $parameter): string => parameterText($parameter, $namespace),
        $method->getParameters(),
    );
    $returns = typeText($method->getReturnType(), $namespace);
    // An interface method is abstract without saying so.
    $isAbstract = $method->isAbstract() && !$class->isInterface();
    $modifiers = ($isAbstract ? 'abstract ' : '') . ($method->isFinal() ? 'final ' : '')
        . 'public ' . ($method->isStatic() ? 'static ' : '');

    return "{$modifiers}function {$method->name}(" . \implode(', ', $parameters) . ')'
        . ($returns === '' ? '' : ": {$returns}") . ';';
}

/**
 * @param ReflectionClass<object> $class
 *
 * @return list<string>
 */
function methodLines(ReflectionClass $class, string $namespace): array
{
    $lines = [];
    foreach ($class->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
        $isOwn = $method->getDeclaringClass()->name === $class->name;
        $isImplicit = $class->isEnum() && \in_array($method->name, ENUM_METHODS, true);
        if ($isOwn && !$isImplicit && !isInternal($method->getDocComment())) {
            $lines[] = methodLine($class, $method, $namespace);
        }
    }

    return $lines;
}

function clause(string $keyword, string $names): string
{
    return $names === '' ? '' : " {$keyword} {$names}";
}

/**
 * The interfaces that the symbol names itself. A parent class gives the others, and PHP adds two
 * to each enum.
 *
 * @param ReflectionClass<object> $class
 */
function interfaceNames(ReflectionClass $class, string $namespace): string
{
    $parent = $class->getParentClass();
    $inherited = $parent === false ? [] : $parent->getInterfaceNames();
    $names = \array_diff($class->getInterfaceNames(), $inherited, ENUM_INTERFACES);
    \sort($names);

    return \implode(', ', \array_map(
        static fn(string $name): string => relativeName($name, $namespace),
        $names,
    ));
}

/**
 * @param ReflectionClass<object> $class
 */
function classHeader(ReflectionClass $class, string $namespace): string
{
    $name = $class->getShortName();
    $interfaces = interfaceNames($class, $namespace);
    if ($class->isInterface()) {
        return "interface {$name}" . clause('extends', $interfaces);
    }
    $parent = $class->getParentClass();
    $tail = clause('extends', $parent === false ? '' : relativeName($parent->name, $namespace))
        . clause('implements', $interfaces);
    if ($class instanceof ReflectionEnum) {
        $backing = $class->getBackingType();

        return "enum {$name}" . ($backing === null ? '' : ": {$backing}") . $tail;
    }

    return ($class->isAbstract() ? 'abstract ' : '') . ($class->isFinal() ? 'final ' : '')
        . "class {$name}{$tail}";
}

/**
 * @param ReflectionClass<object> $class
 *
 * @return list<string>
 */
function classBlock(ReflectionClass $class, string $namespace): array
{
    $members = [
        ...caseLines($class, $namespace),
        ...publicConstantLines($class, $namespace),
        ...propertyLines($class, $namespace),
        ...methodLines($class, $namespace),
    ];

    return [
        classHeader($class, $namespace),
        '{',
        ...\array_map(static fn(string $member): string => "    {$member}", $members),
        '}',
    ];
}

/**
 * @return list<string> The lines of the dump.
 */
function dumpLines(string $root): array
{
    $composer = readComposerJson($root);
    $package = $composer['name'] ?? null;
    if (!\is_string($package)) {
        throw new RuntimeException('composer.json needs a name.');
    }
    $folders = psr4Folders($composer, $root);
    registerAutoloader($folders);
    $lines = ["# API dump of {$package}", '', DUMP_NOTE, '', '```php'];
    $previous = null;
    foreach (classNames($folders) as $name) {
        $class = reflectSymbol($name);
        $namespace = $class->getNamespaceName();
        if (isInternal($class->getDocComment())) {
            continue;
        }
        if ($namespace !== $previous) {
            $gap = $previous === null ? [] : [''];
            $lines = [...$lines, ...$gap, "namespace {$namespace};", ''];
            $previous = $namespace;
        } else {
            $lines[] = '';
        }
        $lines = [...$lines, ...classBlock($class, $namespace)];
    }

    return [...$lines, '```'];
}

/**
 * @param list<string> $arguments
 */
function dumpApi(string $root, array $arguments): int
{
    $unknown = \array_values(\array_diff($arguments, ['--check']));
    if ($unknown !== []) {
        \fwrite(\STDERR, "Unknown argument {$unknown[0]}. Use --check or no argument.\n");

        return 2;
    }
    $path = "{$root}/" . DUMP_FILE;
    try {
        $text = \implode("\n", dumpLines($root)) . "\n";
        if ($arguments === [] && \file_put_contents($path, $text) === false) {
            throw new RuntimeException('Cannot write ' . DUMP_FILE . '.');
        }
    } catch (RuntimeException $problem) {
        \fwrite(\STDERR, $problem->getMessage() . "\n");

        return 2;
    }
    if ($arguments !== [] && (!\is_file($path) || \file_get_contents($path) !== $text)) {
        \fwrite(\STDERR, DUMP_FILE . " is out of date. Run composer api:dump.\n");

        return 1;
    }

    return 0;
}

exit(dumpApi(\dirname(__DIR__), \array_slice($argv, 1)));
