<?php

// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

// Writes docs/api-dump.md: the public symbols of the package, read by reflection. These are the
// classes, interfaces and enums that composer.json maps to a folder, outside any Internal
// namespace, with their public constants, cases, properties and methods. Run `composer api:dump`
// after a change of the public interface (NPG-5, GIT-7). `composer api:dump:check` fails when the
// file is out of date. The script finds its classes through the PSR-4 map of composer.json and
// loads them with its own autoloader, so it needs no installed package.

namespace Gatepost\Postcode\Scripts;

require __DIR__ . '/dump-api-symbols.php';

use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionEnum;
use RuntimeException;
use SplFileInfo;

const DUMP_FILE = 'docs/api-dump.md';
const INTERNAL_NAMESPACE = 'Internal';
const DUMP_NOTE = 'Do not edit this file. `composer api:dump` writes it from the public symbols of '
    . 'the package. It leaves out each `Internal` namespace and each symbol with `@internal` in '
    . 'its doc comment. It shows native types only, so a type that only a doc comment gives is '
    . 'not here. `composer api:dump:check` fails when this file is out of date.';

/**
 * @return array<mixed>
 */
function readComposerJson(string $root): array
{
    $path = "{$root}/composer.json";
    $json = \is_file($path) && \is_readable($path) ? \file_get_contents($path) : false;
    $composer = $json === false ? null : \json_decode($json, true);
    if (!\is_array($composer)) {
        throw new RuntimeException('Cannot read composer.json.');
    }

    return $composer;
}

/**
 * @param array<mixed> $composer
 *
 * @return array<string, string> Each PSR-4 prefix with its folder.
 */
function psr4Folders(array $composer, string $root): array
{
    $autoload = $composer['autoload'] ?? null;
    $map = \is_array($autoload) ? ($autoload['psr-4'] ?? null) : null;
    if (!\is_array($map) || $map === []) {
        throw new RuntimeException('composer.json needs an autoload.psr-4 map.');
    }
    $folders = [];
    foreach ($map as $prefix => $folder) {
        if (!\is_string($prefix) || !\is_string($folder)) {
            throw new RuntimeException('Each PSR-4 entry of composer.json must name one folder.');
        }
        $folders[$prefix] = $root . '/' . \rtrim($folder, '/');
    }

    return $folders;
}

/**
 * @param array<string, string> $folders
 */
function registerAutoloader(array $folders): void
{
    \spl_autoload_register(static function (string $name) use ($folders): void {
        foreach ($folders as $prefix => $folder) {
            $file = $folder . '/' . \str_replace('\\', '/', \substr($name, \strlen($prefix)));
            if (\str_starts_with($name, $prefix) && \is_file("{$file}.php")) {
                require_once "{$file}.php";
            }
        }
    });
}

/**
 * @param array<string, string> $folders
 *
 * @return list<string> Each class name that the PSR-4 map gives to a file outside Internal.
 */
function classNames(array $folders): array
{
    $names = [];
    foreach ($folders as $prefix => $folder) {
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($folder, FilesystemIterator::SKIP_DOTS),
        );
        foreach ($files as $file) {
            if (!$file instanceof SplFileInfo || $file->getExtension() !== 'php') {
                continue;
            }
            $path = \substr($file->getPathname(), \strlen($folder) + 1, -\strlen('.php'));
            $segments = \explode(\DIRECTORY_SEPARATOR, \dirname($path));
            if (!\in_array(INTERNAL_NAMESPACE, $segments, true)) {
                $names[] = $prefix . \str_replace(\DIRECTORY_SEPARATOR, '\\', $path);
            }
        }
    }
    \sort($names);

    return $names;
}

/**
 * @return ReflectionClass<object>
 */
function reflectSymbol(string $name): ReflectionClass
{
    if (\enum_exists($name)) {
        return new ReflectionEnum($name);
    }
    if (!\class_exists($name) && !\interface_exists($name)) {
        throw new RuntimeException(
            "{$name} is not a class, an interface or an enum. "
            . 'Check that the file name follows the class name.',
        );
    }

    return new ReflectionClass($name);
}

/**
 * @return list<string> The lines of the dump.
 */
function dumpLines(string $root): array
{
    $composer = readComposerJson($root);
    $package = $composer['name'] ?? null;
    if (!\is_string($package)) {
        throw new RuntimeException('composer.json needs a name.');
    }
    $folders = psr4Folders($composer, $root);
    registerAutoloader($folders);
    $lines = ["# API dump of {$package}", '', DUMP_NOTE, '', '```php'];
    $previous = null;
    foreach (classNames($folders) as $name) {
        $class = reflectSymbol($name);
        $namespace = $class->getNamespaceName();
        if (isInternal($class->getDocComment())) {
            continue;
        }
        if ($namespace !== $previous) {
            $gap = $previous === null ? [] : [''];
            $lines = [...$lines, ...$gap, "namespace {$namespace};", ''];
            $previous = $namespace;
        } else {
            $lines[] = '';
        }
        $lines = [...$lines, ...classBlock($class, $namespace)];
    }

    return [...$lines, '```'];
}

/**
 * @param list<string> $arguments
 */
function dumpApi(string $root, array $arguments): int
{
    $unknown = \array_values(\array_diff($arguments, ['--check']));
    if ($unknown !== []) {
        \fwrite(\STDERR, "Unknown argument {$unknown[0]}. Use --check or no argument.\n");

        return 2;
    }
    $path = "{$root}/" . DUMP_FILE;
    try {
        $text = \implode("\n", dumpLines($root)) . "\n";
        if ($arguments === [] && \file_put_contents($path, $text) === false) {
            throw new RuntimeException('Cannot write ' . DUMP_FILE . '.');
        }
    } catch (RuntimeException $problem) {
        \fwrite(\STDERR, $problem->getMessage() . "\n");

        return 2;
    }
    if ($arguments !== [] && (!\is_file($path) || \file_get_contents($path) !== $text)) {
        \fwrite(\STDERR, DUMP_FILE . " is out of date. Run composer api:dump.\n");

        return 1;
    }

    return 0;
}

exit(dumpApi(\dirname(__DIR__), \array_slice($argv, 1)));
