<?php

// SPDX-FileCopyrightText: 2026 The Gatepost authors
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

// Writes the generated classes in src/Internal: SpecData.php from the JSON files in spec/data,
// and NfkcTable.php from the Unicode Character Database and the separators in
// spec/data/format.json. Run `composer generate` after the spec submodule changes.
// `composer generate:check` fails when a file is out of date. This file holds the entry point
// and the helpers that write PHP source.

namespace Gatepost\Postcode\Scripts;

use RuntimeException;

require __DIR__ . '/spec-data.php';
require __DIR__ . '/nfkc-table.php';

const ENTRY = '        ';
// These lines are the SPDX tags of SpecData.php. Inside this script they end in a quote and a
// comma, so REUSE rejects them unless it skips them.
// REUSE-IgnoreStart
const GATEPOST_TAGS = [
    '// SPDX-FileCopyrightText: 2026 The Gatepost authors',
    '// SPDX-License-Identifier: Apache-2.0',
];
// REUSE-IgnoreEnd

/**
 * @param list<string> $arguments
 */
function main(string $root, array $arguments): int
{
    $unknown = \array_values(\array_diff($arguments, ['--check']));
    if ($unknown !== []) {
        \fwrite(STDERR, "Unknown argument {$unknown[0]}. Use --check or no argument.\n");

        return 2;
    }
    $format = readJson("{$root}/" . FORMAT_FILE);
    $separators = separatorCodePoints($format['separators'] ?? null);
    $files = [
        'src/Internal/SpecData.php' => specData($root, $format, $separators),
        'src/Internal/NfkcTable.php' => nfkcTable(unicodeData($root), $separators),
    ];
    if ($arguments === []) {
        foreach ($files as $path => $contents) {
            writeFile("{$root}/{$path}", $contents);
        }

        return 0;
    }
    $stale = \array_filter(
        \array_keys($files),
        static fn(string $path): bool => !\is_file("{$root}/{$path}")
            || \file_get_contents("{$root}/{$path}") !== $files[$path],
    );
    foreach ($stale as $path) {
        \fwrite(STDERR, "{$path} is out of date. Run composer generate.\n");
    }

    return $stale === [] ? 0 : 1;
}

function writeFile(string $path, string $contents): void
{
    if (!\is_dir(\dirname($path))) {
        \mkdir(\dirname($path), 0o777, true);
    }
    if (\file_put_contents($path, $contents) === false) {
        throw new RuntimeException("Cannot write {$path}.");
    }
}

function quoted(string $ascii): string
{
    return "'" . \strtr($ascii, ['\\' => '\\\\', "'" => "\\'"]) . "'";
}

/**
 * @param list<int> $codePoints
 */
function escaped(array $codePoints): string
{
    $literal = '';
    foreach ($codePoints as $codePoint) {
        $printable = $codePoint >= 0x20 && $codePoint <= 0x7E;
        $special = \in_array($codePoint, [0x22, 0x24, 0x5C], true);
        $literal .= $printable && !$special ? \chr($codePoint) : \sprintf('\u{%04X}', $codePoint);
    }

    return '"' . $literal . '"';
}

/**
 * @param string|list<string> $value A PHP literal, or the entry lines of an array.
 *
 * @return list<string>
 */
function constantLines(string $summary, string $name, string|array $value): array
{
    $doc = ['', '    /**', "     * {$summary}", '     */'];
    if (\is_string($value)) {
        return [...$doc, "    public const {$name} = {$value};"];
    }

    return [...$doc, "    public const {$name} = [", ...$value, '    ];'];
}

/**
 * @param list<string> $tags The SPDX tags of the file.
 *
 * @return list<string>
 */
function fileHeader(string $source, array $tags): array
{
    return [
        '<?php',
        '',
        // check-tells exempts a generated file from TELL-1, but it reads only the first five
        // lines for this marker. The tags follow the marker, so that a file with more tags
        // still keeps the marker on line 5 or earlier.
        "// @generated by scripts/generate-data.php from {$source}. Do not edit this file.",
        ...$tags,
        '',
    ];
}

/**
 * @param list<string> $header The lines before the strict_types declaration.
 * @param list<string> $constants
 */
function classFile(array $header, string $summary, string $class, array $constants): string
{
    return \implode("\n", [
        ...$header,
        'declare(strict_types=1);',
        '',
        'namespace Gatepost\Postcode\Internal;',
        '',
        '/**',
        " * {$summary}",
        ' *',
        ' * @internal',
        ' */',
        "final class {$class}",
        '{',
        // constantLines() starts each constant with a blank line. Drop the first one, which
        // would follow the opening brace.
        ...\array_slice($constants, 1),
        '}',
        '',
    ]);
}

exit(main(\dirname(__DIR__), \array_slice($argv, 1)));
